version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: shopperuserteste
      POSTGRES_PASSWORD: senha8877MNPQ
      POSTGRES_DB: shopper-exclusive-teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: >
      sh -c "
      npx prisma generate &&
      npm run seed &&
      npm run dev
      "
    environment:
      DATABASE_URL: "postgresql://shopperuserteste:senha8877MNPQ@db:5432/shopper-exclusive-teste"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data:
