version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}" 
    depends_on:
      - db
    volumes:
      - .:/app
    command: "npm run dev"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
